### ISSUE TITLE
Create more tests for views.

### ISSUE THREAD

**Issue by Chayapol-c** [Bouncyyahomie/TEWMA-project#32]
Create tests for `appointment/views.py`
### IndexViewTest
- If the user is **not** authenticated, show Welcome, AnonymousUser
- If the argument in get_date() is **not** date object (str) return a date object with a specific date
### MeetingListTest
- If no meeting should see noting
- If has end meeting but access in wrong URL should see noting.
- If has future meeting but access in the wrong URL should see nothing.
- If access to the correct URL and has a meeting on that day should see the detail.
### MeetingDetailView
- Even after the meeting's closing days, the user still sees that meeting.
- Users can see future meetings.

**Comment by nuttapol-kor** [comment]
This task is done. codecov 97.15% (+2.76%) compared to 7382b19
