### ISSUE TITLE
Iteration 5 Plan doccument

### ISSUE THREAD

**Issue by Chayapol-c** [Bouncyyahomie/TEWMA-project#54]
- plan on the wiki page.
- create tasks in Github projects

**Comment by nuttapol-kor** [comment]
I add a plan in [Iteration 5 Plan](https://github.com/Bouncyyahomie/TEWMA-project/wiki/Iteration%205%20Plan) (The user can create his own appointment), so I close this task for now. If anyone wants to add some plan more can reopen this task.
