### ISSUE TITLE
Improving user creation.

### ISSUE THREAD

**Issue by Chayapol-c** [Bouncyyahomie/TEWMA-project#55]
- make a new model to handle users in one meeting.

**Comment by nuttapol-kor** [comment]
This task I add 2 commit 
- In 9cebf4d I add UserMeeting model and `0004_usermeeting.py` file for handle users in one meeting.
- In eea5131 everything in this commit for the join button in detail page can work and set the MESSAGE_TAGS setting
so I close this task for now
