### ISSUE TITLE
Create tests for Meeting [20 mins]

### ISSUE THREAD

**Issue by Chayapol-c** [Bouncyyahomie/TEWMA-project#7]
- Test representation of the Meeting object
- Can get a URL from the Meeting object?
- Can get the meeting date?

**Comment by nuttapol-kor** [comment]
I add `test_str_meeting()`, `test_get_html_url_from_meeting()`, `test_get_meeting_date()` for the **MeetingModelTest class**, 
and add some docstring each test in `appointment/tests.py`. So I close this task.
