### ISSUE TITLE
Minor usability issues.

### ISSUE THREAD

**Issue by Sahadporn** [Bouncyyahomie/TEWMA-project#96]
url: https://tewma-meeting.herokuapp.com/meeting/new

1. There is no restriction on how many characters description can contain. And the description overflow out of the container.
2. I can set the meeting date 1300 years from now.
![tewma1](https://user-images.githubusercontent.com/59825486/101124457-b4cfac00-3629-11eb-90d0-a6ffa2a8ac45.png)

3. I can set the event's end date before the event's start date.
![image](https://user-images.githubusercontent.com/59825486/101124813-52c37680-362a-11eb-9499-7c37e7323293.png)

**Comment by nuttapol-kor** [comment]
Thanks for your advice. We fixed it.
